#!/usr/bin/env bash
# Calibration harness for the Dark Factory auditor against the EVM/Solidity corpus (M4 of
# agentis-core#858). The EVM peer of calibrate-sealevel.sh: it runs the .ag colony's full
# detect -> synthesize -> verify pipeline (run-audit.sh) over the five-class vuln+safe corpus
# in evm-harness/contracts/ and writes a scorecard — per class + variant, the auditor's verdict
# through the REAL EVM (revm).
#
#   - VULN contracts must reach VERIFIED via a compiling two-sided revm PoC (true positive).
#   - SAFE variants must reach SAFE — they must NOT reach VERIFIED (zero false-VERIFIED is the
#     hard blocker: a false-VERIFIED on a safe target is a ban-list risk on a live platform).
#
# Detection uses the configured LLM backend (the real classify_evm_llm). With the default
# under a reasoning backend (the default flat-cyborg, or claude) each class routes to its specific
# invariant; the mock backend has no class router (it falls back to the structural reentrancy
# heuristic), so the per-class true-positive tally is only meaningful under a reasoning backend —
# run with the default BACKEND to populate the scorecard.
# The two-sided gate (CONTROL OK: + INVARIANT VIOLATED: + exit 101) is what makes a safe variant
# resolve to a non-VERIFIED verdict even if detection over-flags it.
#
# Usage: AGENTIS=/path/to/agentis [BACKEND=flat-cyborg] [EVM_HARNESS_DIR=/path/to/warm/harness] \
#        ./calibrate-evm.sh [out.md]
set -u

HERE="$(cd "$(dirname "$0")" && pwd)"
AGENTIS="${AGENTIS:-agentis}"
BACKEND="${BACKEND:-flat-cyborg}"
HARNESS="${EVM_HARNESS_DIR:-$HERE/evm-harness}"
CORPUS="$HERE/evm-harness/contracts"
OUT="${1:-$HERE/evm-scorecard.md}"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

# class | vuln contract (must VERIFY) | safe contract (must NOT verify)
CLASSES=(
  "Reentrancy|ReentrancyVaultInsecure.sol|ReentrancyVaultSecure.sol"
  "AccessControl|AccessControlVaultInsecure.sol|AccessControlVaultSecure.sol"
  "UncheckedCall|UncheckedCallVaultInsecure.sol|UncheckedCallVaultSecure.sol"
  "OracleManipulation|OracleVaultInsecure.sol|OracleVaultSecure.sol"
  "IntegerOverflow|OverflowVaultInsecure.sol|OverflowVaultSecure.sol"
)

# Run the colony once over <contract.sol> via run-audit.sh; echo the parsed verdict token.
run_one() {
  contract="$1"
  d="$WORK/${contract%.sol}"
  mkdir -p "$d"
  env BACKEND="$BACKEND" AGENTIS="$AGENTIS" \
    "$HERE/run-audit.sh" \
      --target "$CORPUS/$contract" \
      --evm-harness "$HARNESS" \
      --backend "$BACKEND" \
      --agentis "$AGENTIS" \
      --out "$d" \
      > "$d/run.log" 2>&1
  verdict="$(grep -oE 'VERDICT: [A-Z]+' "$d/run.log" 2>/dev/null | tail -1 | awk '{print $2}')"
  [ -z "$verdict" ] && verdict="ERROR"
  echo "$verdict"
}

tp=0; false_verified=0; false_safe=0; rows=""
for entry in "${CLASSES[@]}"; do
  cls="${entry%%|*}"; rest="${entry#*|}"
  vuln="${rest%%|*}"; safe="${rest##*|}"

  echo "[calibrate-evm] $cls — vuln ($vuln) ..." >&2
  vuln_v="$(run_one "$vuln")"
  echo "[calibrate-evm] $cls — safe ($safe) ..." >&2
  safe_v="$(run_one "$safe")"

  vuln_mark="OK"
  if [ "$vuln_v" = "VERIFIED" ]; then tp=$((tp+1)); else vuln_mark="MISS"; fi

  safe_mark="OK"
  if [ "$safe_v" = "VERIFIED" ]; then
    false_verified=$((false_verified+1)); safe_mark="FALSE-VERIFIED"
  elif [ "$safe_v" != "SAFE" ]; then
    false_safe=$((false_safe+1)); safe_mark="NON-SAFE"
  fi

  rows="${rows}| \`${cls}\` | ${vuln} → **${vuln_v}** (${vuln_mark}) | ${safe} → **${safe_v}** (${safe_mark}) |
"
done

pass="FAIL"
if [ "$tp" -ge 5 ] && [ "$false_verified" -eq 0 ]; then pass="PASS"; fi

{
  echo "# Dark Factory — EVM calibration scorecard"
  echo
  echo "Generated by \`calibrate-evm.sh\` over the five-class vuln+safe corpus in"
  echo "\`evm-harness/contracts/\`. Detection is the real \`classify_evm_llm\` (backend=${BACKEND});"
  echo "each verdict is the auditor's two-sided gate over a compiling \`revm\` PoC run through the"
  echo "real EVM (\`CONTROL OK:\` + \`INVARIANT VIOLATED:\` + \`exit 101\`)."
  echo
  echo "| Class | Vuln (must VERIFY) | Safe (must NOT verify) |"
  echo "|---|---|---|"
  printf '%s' "$rows"
  echo
  echo "**True-positive VERIFIED (vuln): ${tp}/5.  False-VERIFIED (safe): ${false_verified}.  Non-SAFE (safe): ${false_safe}.  Result: ${pass}.**"
  echo
  echo "_Done-criterion (#858 M4): 5/5 true-positive VERIFIED on the vuln corpus with compiling"
  echo "revm PoCs, ZERO false-VERIFIED on the safe variants, and every safe variant resolving to SAFE._"
} > "$OUT"

echo "[calibrate-evm] wrote $OUT (tp=$tp false_verified=$false_verified false_safe=$false_safe result=$pass)" >&2
[ "$pass" = "PASS" ]
