#!/usr/bin/env bash
# Calibration harness for the Dark Factory auditor against coral-xyz/sealevel-attacks
# (V6 / #844). Runs the .ag colony's full detect -> validate pipeline over the modernized
# (anchor 0.31) lesson corpus and writes a scorecard: per lesson + variant, the detected
# vulnerability class and the auditor's verdict.
#
#   - INSECURE lessons must reach VERIFIED via a compiling two-sided PoC through the REAL
#     SVM (true positive).
#   - SECURE variants must NOT reach VERIFIED (zero false-VERIFIED is the hard blocker —
#     a false-VERIFIED on a secure target is a ban-list risk).
#
# Detection uses the configured LLM backend (the real classify_llm). The two-sided PoC is
# the committed, harness-validated exploit per lesson (sealevel/<lesson>/poc.rs), supplied
# via BOUNTY_POC so the scorecard is reproducible; the auditor's autonomous LLM PoC
# generation is demonstrated end-to-end separately (lesson 0). The two-sided gate is what
# makes a secure variant resolve to inconclusive even if detection over-flags it.
#
# Usage: AGENTIS=/path/to/agentis SOLANA_ANCHOR_HARNESS_DIR=/path/to/warm/harness \
#        ./calibrate-sealevel.sh [out.md]
set -u

HERE="$(cd "$(dirname "$0")" && pwd)"
AGENTIS="${AGENTIS:-agentis}"
HARNESS="${SOLANA_ANCHOR_HARNESS_DIR:-$HERE/solana-harness-anchor}"
CORPUS="$HERE/sealevel"
OUT="${1:-$HERE/sealevel-scorecard.md}"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

# lesson dir | expected vuln class (the class an insecure variant should detect)
LESSONS=(
  "0-signer-authorization|MissingSignerCheck"
  "1-account-data-matching|AccountDataMatching"
  "2-owner-checks|MissingOwnerCheck"
)

# Run the colony once over <lesson> <variant>; echo "<detected_class>|<verdict>".
run_one() {
  lesson="$1"; variant="$2"
  d="$WORK/$lesson-$variant"
  mkdir -p "$d"
  cp "$HERE/auditor/agents/auditor.ag" "$d/auditor.ag"
  (
    cd "$d" || exit 1
    "$AGENTIS" init >/dev/null 2>&1
    printf '%s\n' \
      'llm.backend = flat-cyborg' \
      'llm.cli_timeout_ms = 180000' 'trace.level = quiet' \
      'exec.env_passthrough = BOUNTY_TARGET,BOUNTY_POC,SOLANA_ANCHOR_HARNESS_DIR' \
      'exec.default_timeout_ms = 180000' > .agentis/config
    env BOUNTY_TARGET="$CORPUS/$lesson/$variant.rs" \
        BOUNTY_POC="$CORPUS/$lesson/poc.rs" \
        SOLANA_ANCHOR_HARNESS_DIR="$HARNESS" \
        timeout 300 "$AGENTIS" go auditor.ag --enable-exec --enable-messaging \
        > run.log 2>&1
  )
  cls="$(grep -oE 'guard: [A-Za-z]+ fired' "$d/run.log" 2>/dev/null | head -1 | awk '{print $2}')"
  [ -z "$cls" ] && cls="none"
  verdict="$(grep -oE 'Verdict: [A-Z]+' "$d/run.log" 2>/dev/null | head -1 | awk '{print $2}')"
  [ -z "$verdict" ] && verdict="ERROR"
  echo "$cls|$verdict"
}

tp=0; false_verified=0; rows=""
for entry in "${LESSONS[@]}"; do
  lesson="${entry%%|*}"; expected="${entry##*|}"
  echo "[calibrate] $lesson (insecure) ..." >&2
  ins="$(run_one "$lesson" insecure)"; ins_cls="${ins%%|*}"; ins_v="${ins##*|}"
  echo "[calibrate] $lesson (secure) ..." >&2
  sec="$(run_one "$lesson" secure)"; sec_cls="${sec%%|*}"; sec_v="${sec##*|}"

  ins_mark="OK"; [ "$ins_v" = "VERIFIED" ] && tp=$((tp+1)) || ins_mark="MISS"
  sec_mark="OK"; [ "$sec_v" = "VERIFIED" ] && { false_verified=$((false_verified+1)); sec_mark="FALSE-VERIFIED"; }

  rows="${rows}| \`${lesson}\` | ${expected} | ${ins_cls} → **${ins_v}** (${ins_mark}) | ${sec_cls} → **${sec_v}** (${sec_mark}) |
"
done

pass="FAIL"
[ "$tp" -ge 3 ] && [ "$false_verified" -eq 0 ] && pass="PASS"

{
  echo "# Dark Factory — sealevel-attacks calibration scorecard"
  echo
  echo "Generated by \`calibrate-sealevel.sh\` over the modernized (anchor 0.31) lesson corpus"
  echo "in \`sealevel/\`. Detection is the real \`classify_llm\`; each verdict is the auditor's"
  echo "two-sided gate over a compiling PoC run through the real \`solana-program-test\` SVM."
  echo
  echo "| Lesson | Expected class | Insecure (must VERIFY) | Secure (must NOT verify) |"
  echo "|---|---|---|---|"
  printf '%s' "$rows"
  echo
  echo "**True-positive VERIFIED (insecure): ${tp}/3.  False-VERIFIED (secure): ${false_verified}.  Result: ${pass}.**"
  echo
  echo "_Done-criterion (#844): >=3 true-positive VERIFIED on real known-vuln lessons with"
  echo "compiling SVM PoCs, and ZERO false-VERIFIED on the secure variants._"
} > "$OUT"

echo "[calibrate] wrote $OUT (tp=$tp false_verified=$false_verified result=$pass)" >&2
[ "$pass" = "PASS" ]
