#!/bin/bash
# install.sh: idempotent setup for this federation.
#
# Stub generated by tools/new-federation.sh. Replace with the federation's
# real prerequisites + credential prompts + memo seeding. Must exit 0 when
# the federation is ready to start.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
FED_NAME="$(basename "$SCRIPT_DIR")"

echo "Installing $FED_NAME federation..."
echo
echo "TODO: implement prerequisite checks, config copying, credential prompts,"
echo "memo seeding, and (optionally) federation-dashboard install per the"
echo ".dashboard-version pin."
echo
echo "For each colony under $SCRIPT_DIR/, copy:"
echo "  <colony>/config/colony.example.toml -> <colony>/config/colony.toml"
echo "and edit the [forge] / data-source / [llm] sections."
echo
echo "Done."
