#!/usr/bin/env python3
# foundry_shim.py — #2277. Turns a HARDHAT-ONLY project root (hardhat.config.*, no foundry.toml) into a generated
# FOUNDRY SHIM WORKING COPY, so the Foundry-only stateful lenses (STAGE 4.5 deep hunt, STAGE 4.6 vector hunt) can run
# on it instead of silently skipping it. lib/foundry-shim.sh is the only caller; it builds one shim per root under
# <out>/.foundry-shim/<slug>/ and probes it with a single `forge build`.
#
# THE TARGET IS FROZEN. Nothing is ever written under --root / --clone: the shim is a COPY (the root's .sol/.md
# sources, a pruned .sol-only node_modules, and a generated foundry.toml + remappings). The Hardhat config is parsed
# with static regexes only — it is target code and is NEVER executed (no node, no require).
#
# Subcommands (python3 stdlib only; the lib/ manual-flag idiom, no argparse):
#   plan  --root <dir> --clone <dir> [--node-modules <dir>]... [--exclude <dir>]...
#       Prints `key=value` lines: config= src= solc_declared= optimizer= optimizer_runs= via_ir= evm_version=,
#       one `remap=<prefix>=<path>` per remapping, one `unresolved=<pkg>` per package an import needs but no search
#       path provides, and `lockfile=<abs>` + `lock_tool=npm|yarn|pnpm` when a lockfile sits in the root or an
#       ancestor up to --clone. Writes nothing (the resolution runs over a temporary copy that is deleted).
#   build --root <dir> --clone <dir> --dest <dir> [--node-modules <dir>]... [--exclude <dir>]...
#       Writes the working copy into --dest (refused when --dest exists and is not empty) and prints the same lines.
#       Exit 0 = built and every import resolves; 4 = built but deps are missing (the `unresolved=` lines name them).
#
# Copy rules: every *.sol / *.md under --root keeps its relative path, plus a root-level remappings.txt. Pruned: dirs
# named node_modules artifacts cache out .git typechain typechain-types coverage .foundry-shim, every --exclude dir
# and --dest itself, and .sol files under a top-level test/ or tests/ (Hardhat's JS test tree, not the compile unit).
# The Hardhat config is not copied, so evm-harness/detect-toolchain.sh resolves the shim as a Foundry project.
#
# Dependency search order: the --node-modules dirs, then <root>/node_modules, then each ancestor's node_modules up to
# --clone (yarn/npm hoisting). The nearest match wins per package name (`@scope/name` expanded). Only packages holding
# at least one .sol are copied (.sol files only, following pnpm symlinks with a realpath cycle guard) and remapped.
#
# Exit: 0 ok; 2 usage error; 3 I/O error; 4 (build) built but deps missing.
import os
import re
import shutil
import sys
import tempfile

SKIP_DIRS = ("node_modules", "artifacts", "cache", "out", ".git", "typechain", "typechain-types", "coverage",
             ".foundry-shim")
TEST_DIRS = ("test", "tests")
CONFIG_FILES = ("hardhat.config.ts", "hardhat.config.js", "hardhat.config.cjs", "hardhat.config.mjs")
# Nearest directory wins; within one directory this order decides.
LOCKFILES = (("package-lock.json", "npm"), ("npm-shrinkwrap.json", "npm"), ("yarn.lock", "yarn"),
             ("pnpm-lock.yaml", "pnpm"))
MARKER = "# generated by dark-factory lib/foundry_shim.py (#2277) — not part of the target"


def die(rc, msg):
    sys.stderr.write("foundry_shim.py: " + msg + "\n")
    sys.exit(rc)


def parse_flags(argv, valued, repeated):
    """Manual flag walk (the lib/ helper idiom). <repeated> flags collect every value into a list; unknown flags
    and missing values are usage errors, never silent."""
    out = {k: [] for k in repeated}
    i = 0
    while i < len(argv):
        a = argv[i]
        if a in valued or a in repeated:
            if i + 1 >= len(argv):
                die(2, a + " requires a value")
            if a in repeated:
                out[a].append(argv[i + 1])
            else:
                out[a] = argv[i + 1]
            i += 2
        else:
            die(2, "unknown arg: " + a)
    return out


def _real(p):
    return os.path.realpath(p)


def _strip_comments(text):
    """Drop /* */ blocks and // line comments (a `//` preceded by `:` — a URL inside a string — is kept)."""
    text = re.sub(r"/\*.*?\*/", " ", text, flags=re.S)
    return re.sub(r"(?<![:\w])//[^\n]*", " ", text)


def read_config(root):
    """Static read of the first hardhat.config.* — never executed. Returns a dict of the recorded settings."""
    cfg = {"config": "", "src": "contracts", "solc_declared": "", "optimizer": "", "optimizer_runs": "",
           "via_ir": "", "evm_version": ""}
    path = None
    for name in CONFIG_FILES:
        if os.path.isfile(os.path.join(root, name)):
            path = os.path.join(root, name)
            cfg["config"] = name
            break
    if path is None:
        return cfg
    try:
        with open(path, encoding="utf-8", errors="ignore") as fh:
            text = _strip_comments(fh.read())
    except OSError:
        return cfg
    m = re.search(r"\bsources\s*:\s*[\"'`]([^\"'`]+)[\"'`]", text)
    if m:
        src = m.group(1).strip().replace("\\", "/")
        while src.startswith("./"):
            src = src[2:]
        src = src.rstrip("/")
        if src and not src.startswith("/") and ".." not in src.split("/") \
                and os.path.isdir(os.path.join(root, src)):
            cfg["src"] = src
    versions = []
    for v in re.findall(r"\b(?:solidity|version)\s*:\s*[\"'](\d+\.\d+\.\d+)[\"']", text):
        if v not in versions:
            versions.append(v)
    cfg["solc_declared"] = ",".join(versions)
    m = re.search(r"\boptimizer\s*:\s*\{([^}]*)\}", text, flags=re.S)
    if m:
        e = re.search(r"\benabled\s*:\s*(true|false)\b", m.group(1))
        r = re.search(r"\bruns\s*:\s*(\d+)", m.group(1))
        cfg["optimizer"] = e.group(1) if e else ""
        cfg["optimizer_runs"] = r.group(1) if r else ""
    ir = re.findall(r"\bviaIR\s*:\s*(true|false)\b", text)
    if ir:
        cfg["via_ir"] = "true" if "true" in ir else "false"
    m = re.search(r"\bevmVersion\s*:\s*[\"']([A-Za-z0-9]+)[\"']", text)
    if m:
        cfg["evm_version"] = m.group(1)
    return cfg


def ancestors(root, clone):
    """<root>, then each ancestor dir up to and including <clone> (only when <root> lies under <clone>)."""
    out = [root]
    r, c = _real(root), _real(clone)
    if r != c and not r.startswith(c + os.sep):
        return out
    cur = root
    while _real(cur) != c:
        parent = os.path.dirname(cur.rstrip(os.sep))
        if not parent or parent == cur:
            break
        cur = parent
        out.append(cur)
    return out


def find_lockfile(root, clone):
    for d in ancestors(root, clone):
        for name, tool in LOCKFILES:
            p = os.path.join(d, name)
            if os.path.isfile(p):
                return os.path.abspath(p), tool
    return "", ""


def _has_sol(pkg_dir):
    seen = set()
    for cur, dirs, files in os.walk(pkg_dir, followlinks=True):
        rc = _real(cur)
        if rc in seen:
            dirs[:] = []
            continue
        seen.add(rc)
        dirs[:] = [d for d in dirs if d != "node_modules"]
        if any(f.endswith(".sol") for f in files):
            return True
    return False


def packages(search):
    """{name: package dir} over the search path, nearest first. `@scope/name` is expanded; dot-dirs (.pnpm,
    .bin, ...) are never packages."""
    found = {}
    order = []
    for nm in search:
        if not os.path.isdir(nm):
            continue
        try:
            entries = sorted(os.listdir(nm))
        except OSError:
            continue
        for e in entries:
            if e.startswith("."):
                continue
            full = os.path.join(nm, e)
            if not os.path.isdir(full):
                continue
            if e.startswith("@"):
                try:
                    subs = sorted(os.listdir(full))
                except OSError:
                    continue
                for s in subs:
                    if s.startswith(".") or not os.path.isdir(os.path.join(full, s)):
                        continue
                    name = e + "/" + s
                    if name not in found:
                        found[name] = os.path.join(full, s)
                        order.append(name)
            elif e not in found:
                found[e] = full
                order.append(e)
    return found, order


def copy_sources(root, dest, excludes):
    """Copy every .sol / .md under <root> into <dest> (relative paths kept) + a root-level remappings.txt."""
    ex = set(_real(p) for p in excludes)
    ex.add(_real(dest))
    n = 0
    for cur, dirs, files in os.walk(root):
        keep = []
        for d in sorted(dirs):
            full = os.path.join(cur, d)
            if d in SKIP_DIRS or _real(full) in ex:
                continue
            keep.append(d)
        dirs[:] = keep
        rel_dir = os.path.relpath(cur, root)
        top = "" if rel_dir == "." else rel_dir.replace(os.sep, "/").split("/")[0]
        for f in sorted(files):
            if not (f.endswith(".sol") or f.endswith(".md")):
                continue
            if f.endswith(".sol") and top in TEST_DIRS:
                continue
            src = os.path.join(cur, f)
            dst = os.path.join(dest, rel_dir, f)
            os.makedirs(os.path.dirname(dst), exist_ok=True)
            shutil.copyfile(src, dst)
            n += 1
    rm = os.path.join(root, "remappings.txt")
    if os.path.isfile(rm):
        shutil.copyfile(rm, os.path.join(dest, "remappings.txt"))
    return n


def copy_package(pkg_dir, dst):
    """Copy the .sol files of one package into <dst> (following symlinks, cycle-guarded, nested node_modules
    skipped). Returns the number of files copied."""
    seen = set()
    n = 0
    for cur, dirs, files in os.walk(pkg_dir, followlinks=True):
        rc = _real(cur)
        if rc in seen:
            dirs[:] = []
            continue
        seen.add(rc)
        dirs[:] = sorted(d for d in dirs if d != "node_modules")
        rel = os.path.relpath(cur, pkg_dir)
        for f in sorted(files):
            if f.endswith(".sol"):
                out = os.path.join(dst, rel, f)
                os.makedirs(os.path.dirname(out), exist_ok=True)
                shutil.copyfile(os.path.join(cur, f), out)
                n += 1
    return n


def read_remappings(dest):
    out = []
    p = os.path.join(dest, "remappings.txt")
    if not os.path.isfile(p):
        return out
    with open(p, encoding="utf-8", errors="ignore") as fh:
        for line in fh:
            line = line.strip()
            if line and not line.startswith("#") and "=" in line and line not in out:
                out.append(line)
    return out


def _toml_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def write_foundry_toml(dest, cfg, remaps):
    lines = [MARKER,
             "# source config: %s; declared solc: %s (recorded, NOT pinned: forge auto-detects per pragma)"
             % (cfg["config"] or "-", cfg["solc_declared"] or "-"),
             "[profile.default]",
             "src = " + _toml_str(cfg["src"]),
             'test = "test"',
             'libs = ["node_modules", "lib"]']
    if remaps:
        lines.append("remappings = [")
        lines.extend("    %s," % _toml_str(r) for r in remaps)
        lines.append("]")
    if cfg["optimizer"]:
        lines.append("optimizer = " + cfg["optimizer"])
    if cfg["optimizer_runs"]:
        lines.append("optimizer_runs = " + cfg["optimizer_runs"])
    if cfg["via_ir"]:
        lines.append("via_ir = " + cfg["via_ir"])
    if cfg["evm_version"]:
        lines.append("evm_version = " + _toml_str(cfg["evm_version"]))
    with open(os.path.join(dest, "foundry.toml"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")


IMPORT_RE = re.compile(r"\bimport\s+(?:[^;\"']*?\bfrom\s+)?[\"']([^\"']+)[\"']", re.S)


def _pkg_key(path):
    parts = path.split("/")
    if parts[0].startswith("@") and len(parts) > 1:
        return parts[0] + "/" + parts[1]
    return parts[0]


def unresolved_imports(dest, src, remaps):
    """Walk the import closure from the <src> files inside <dest>. A non-relative import resolves through the
    longest matching remapping, then <dest>/<path>; one that still does not resolve is reported by package key."""
    rules = []
    for r in remaps:
        lhs, rhs = r.split("=", 1)
        if ":" in lhs:
            lhs = lhs.split(":", 1)[1]
        rules.append((lhs, rhs))
    rules.sort(key=lambda t: -len(t[0]))
    todo = []
    src_dir = os.path.join(dest, src)
    for cur, dirs, files in os.walk(src_dir):
        dirs.sort()
        for f in sorted(files):
            if f.endswith(".sol"):
                todo.append(os.path.join(cur, f))
    seen = set()
    missing = []
    while todo:
        path = todo.pop()
        rp = _real(path)
        if rp in seen:
            continue
        seen.add(rp)
        try:
            with open(path, encoding="utf-8", errors="ignore") as fh:
                text = _strip_comments(fh.read())
        except OSError:
            continue
        for imp in IMPORT_RE.findall(text):
            if imp.startswith("./") or imp.startswith("../"):
                cand = os.path.normpath(os.path.join(os.path.dirname(path), imp))
                if os.path.isfile(cand):
                    todo.append(cand)
                continue  # a broken relative import is the forge probe's to report
            hit = None
            for lhs, rhs in rules:
                if imp.startswith(lhs):
                    cand = os.path.join(dest, rhs + imp[len(lhs):])
                    if os.path.isfile(cand):
                        hit = cand
                    break
            if hit is None and os.path.isfile(os.path.join(dest, imp)):
                hit = os.path.join(dest, imp)
            if hit is not None:
                todo.append(hit)
            else:
                key = _pkg_key(imp)
                if key not in missing:
                    missing.append(key)
    return sorted(missing)


def make_shim(root, clone, dest, node_modules, excludes):
    """Write the shim into <dest>; return (cfg, remaps, unresolved)."""
    cfg = read_config(root)
    copy_sources(root, dest, excludes + [dest])
    search = list(node_modules) + [os.path.join(d, "node_modules") for d in ancestors(root, clone)]
    found, order = packages(search)
    copied = []
    for name in order:
        if _has_sol(found[name]):
            if copy_package(found[name], os.path.join(dest, "node_modules", name)):
                copied.append(name)
    remaps = read_remappings(dest)
    covered = set(r.split("=", 1)[0].split(":", 1)[-1] for r in remaps)
    extra = sorted("%s/=node_modules/%s/" % (n, n) for n in copied if (n + "/") not in covered)
    remaps = remaps + extra
    write_foundry_toml(dest, cfg, remaps)
    return cfg, remaps, unresolved_imports(dest, cfg["src"], remaps)


def emit(cfg, remaps, unresolved, lockfile, tool):
    for k in ("config", "src", "solc_declared", "optimizer", "optimizer_runs", "via_ir", "evm_version"):
        sys.stdout.write("%s=%s\n" % (k, cfg[k]))
    for r in remaps:
        sys.stdout.write("remap=%s\n" % r)
    for u in unresolved:
        sys.stdout.write("unresolved=%s\n" % u)
    if lockfile:
        sys.stdout.write("lockfile=%s\nlock_tool=%s\n" % (lockfile, tool))


def _common(flags, sub):
    for req in ("--root", "--clone"):
        if not flags.get(req):
            die(2, sub + " requires --root <dir> --clone <dir>")
    root, clone = os.path.abspath(flags["--root"]), os.path.abspath(flags["--clone"])
    if not os.path.isdir(root):
        die(3, "--root is not a directory: " + root)
    if not os.path.isdir(clone):
        die(3, "--clone is not a directory: " + clone)
    nms = [os.path.abspath(p) for p in flags["--node-modules"]]
    exs = [os.path.abspath(p) for p in flags["--exclude"]]
    return root, clone, nms, exs


def cmd_plan(argv):
    flags = parse_flags(argv, ("--root", "--clone"), ("--node-modules", "--exclude"))
    root, clone, nms, exs = _common(flags, "plan")
    tmp = tempfile.mkdtemp(prefix="foundry-shim-plan.")
    try:
        cfg, remaps, unresolved = make_shim(root, clone, tmp, nms, exs)
    except OSError as e:
        die(3, "plan failed: " + str(e))
    finally:
        shutil.rmtree(tmp, ignore_errors=True)
    lockfile, tool = find_lockfile(root, clone)
    emit(cfg, remaps, unresolved, lockfile, tool)
    return 0


def cmd_build(argv):
    flags = parse_flags(argv, ("--root", "--clone", "--dest"), ("--node-modules", "--exclude"))
    root, clone, nms, exs = _common(flags, "build")
    if not flags.get("--dest"):
        die(2, "build requires --dest <dir>")
    dest = os.path.abspath(flags["--dest"])
    if os.path.exists(dest) and (not os.path.isdir(dest) or os.listdir(dest)):
        die(2, "--dest exists and is not empty (refusing to overwrite): " + dest)
    try:
        os.makedirs(dest, exist_ok=True)
        cfg, remaps, unresolved = make_shim(root, clone, dest, nms, exs)
    except OSError as e:
        die(3, "build failed: " + str(e))
    lockfile, tool = find_lockfile(root, clone)
    emit(cfg, remaps, unresolved, lockfile, tool)
    return 4 if unresolved else 0


def main(argv):
    cmds = {"plan": cmd_plan, "build": cmd_build}
    if len(argv) < 2 or argv[1] not in cmds:
        die(2, "usage: foundry_shim.py {plan|build} --root <dir> --clone <dir> [--dest <dir>] "
               "[--node-modules <dir>]... [--exclude <dir>]...")
    return cmds[argv[1]](argv[2:])


if __name__ == "__main__":
    sys.exit(main(sys.argv))
